name: Build DonRaulAva Project

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    if: true # set false to Temporarily disable the job for pull requests

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Chocolatey
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; `
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      # Step 3: Install VS studio, Cmake, Ninja and so on
      - name: Download and install Visual Studio Installer cmake and so on without choco
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "vs_buildtools.exe"
          ls "C:\Program Files (x86)\Windows Kits\10\bin\*\x64\"
          Start-Process -FilePath ".\vs_buildtools.exe" -ArgumentList @(
            "--quiet", "--wait", "--norestart", "--nocache",
            "--add", "Microsoft.VisualStudio.Workload.VCTools",
            "--add", "Microsoft.VisualStudio.Component.VC.CoreBuildTools",
            "--add", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
            "--add", "Microsoft.VisualStudio.Component.Windows10SDK.${{ inputs.sdk-version }}",
            "--add", "Microsoft.VisualStudio.Component.CMakeTools"
          ) -Wait

      # Step 4: Install other dependencies
      - name: Install Dependencies
        run: |
          choco install nsis -y
          choco install 7zip -y
          choco install ninja -y

      # Step 5: Download OpenCV Prebuilt Binaries
      - name: Download OpenCV 4.11 Prebuilt Binaries
        run: |
          curl -L -o opencv-4.11-windows.exe https://github.com/opencv/opencv/releases/download/4.11.0/opencv-4.11.0-windows.exe
          7z x opencv-4.11-windows.exe -oC:\
          ls C:\opencv
      # Step 6: Configure MSVC Environment and Build with CMake. 
      # Use command Prompt as shell for vcvars64.bat settings
      - name: MSVC Environment and Configure with CMake Preset
        shell: cmd
        run: |
          @echo on 

          :: 1: Set OpenCV directory and update PATH
          echo Setting OpenCV directory...
          set OpenCV_DIR=C:\opencv\build
          set PATH=%PATH%;C:\opencv\build\bin;

          :: 2: Initialize MSVC build environment
          echo Initializing MSVC build environment...
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

          :: 3: Verify tool availability
          echo Verifying tool paths...
          where ninja
          where cmake
          where rc
          where cl

          :: 4: Run CMake commands
          echo Running CMake commands...
          cmake --preset x64-release
          cmake --build --preset build-x64-release

          :: 5: Package the build
          echo Packaging the build...
          cd .\out\build\x64-release\
          cpack

  release:
    runs-on: windows-latest
    needs: build # Ensure the build job completes first
    if: startsWith(github.ref, 'refs/tags/') # Only run this job when it's a tag push

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Create a GitHub Release (Optional)
      # This step ensures the release is explicitly created if needed
      - name: Create Release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "Release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Upload Executable to GitHub Release
      - name: Upload Executable to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/build/x64-release/DonRaulAva--win64.exe
          asset_name: DonRaulAva--win64.exe
          asset_content_type: application/octet-stream
